### ISSUE TITLE
Add Mock Object (with verify)

### ISSUE THREAD

**Issue by AlexDarigan** [AlexDarigan/WAT#122]
With the recent addition of a Callable Func we now have a system for implementing a classic Mock object that verifys itself. We can't do properties just yet (unless they have a predefined setget method we can override/extend).

**Comment by CodeDarigan** [comment]
Going bench this until the next release.

**Comment by AlexDarigan** [comment]
Reopening unresolved issue.

**Comment by AlexDarigan** [comment]
Closing in favor of #285
