### ISSUE TITLE
Add Strict Mock Object

### ISSUE THREAD

**Issue by AlexDarigan** [AlexDarigan/WAT#138]
A Mock Object defines what it expects to be called, how many times and with what arguments. If any of this fails than it fails. It is an assertion in and of itself as well.

**Comment by CodeDarigan** [comment]
In retrospect this doesn't add any features that aren't already covered and surely doesn't make anything simpler.

**Comment by AlexDarigan** [comment]
Reopening unresolved issue.

**Comment by AlexDarigan** [comment]
Closing in favor of #285
