### ISSUE TITLE
Support shallow array comparisons in asserts.is_equal()

### ISSUE THREAD

**Issue by AnmAtAnm** [AlexDarigan/WAT#200]
If the compared object arguments of `asserts.is_equal(..)` are both arrays, check the items of the arrays for equality. Fail if the arrays are not the same size.

**Comment by AlexDarigan** [comment]
I need to be careful with this because I think Godot compares array equality by reference. I'd need to add a way to distinguish them (maybe a default flag?)

**Comment by AlexDarigan** [comment]
Reopening apparently unresolved issue.

**Comment by AlexDarigan** [comment]
Will need to split this into is_same (comparison by ref) and is_equal (comparison by value)
