### ISSUE TITLE
Feature request: Spies/Stubs for static functions and core classes

### ISSUE THREAD

**Issue by ChocolatePinecone** [AlexDarigan/WAT#202]
I'm in the process of writing unit tests for a little project we're setting up, and would love to be able to spy on some global static functions I made.
Also being able to spy/stub methods of core classes like Node2D or Sprite would be incredibly handy for really boxing off tests, minimizing side-effects.

**Comment by AlexDarigan** [comment]
Godot doesn't provide enough reflection to inform me which methods are static or not. However when stubbing a method, you can pass in the static const like this.

![image](https://user-images.githubusercontent.com/47497501/109631078-889acd00-7b3d-11eb-88c0-105a71499730.png)

WAT retrieves methods recursively so you should be able to stub core methods (provided you pass in the correct args) but I'm not 100% on that one.

**Comment by ChocolatePinecone** [comment]
Oh, that's interesting about the static methods! 
I'll give that a try!

So for the core methods, if I understand correctly I could only stub them through a self made derived class?
Since there is no known script location for core classes I could not think of any other way either.

**Comment by AlexDarigan** [comment]
>  Though if the tested function calls the global method directly, there doesn't seem to be a way for the double to take it's place.

I was thinking about that. I could have an early exit option on stubs so they return before calling into the parent method.

> So for the core methods, if I understand correctly I could only stub them through a self made derived class?

If I recall correctly, WAT will double that for you automatically. See https://github.com/AlexDarigan/WAT-GDScript/blob/master/tests/integration/on_floor.test.gd for in use.

> How could I stub a method called this way? I could technically add a layer of abstraction by storing a reference to the global namespace and then replace that by the double when testing

Oh global static methods could get messy. Not sure if I can do that.

**Comment by ChocolatePinecone** [comment]
> If I recall correctly, WAT will double that for you automatically. See https://github.com/AlexDarigan/WAT-GDScript/blob/master/tests/integration/on_floor.test.gd for in use.

So `direct.script("KinematicBody2D")` should work! I'll keep that in mind, thanks!

**Comment by AlexDarigan** [comment]
> 
> 
> Oh, that's interesting about the static methods!
> Though if the tested function calls the global method directly, there doesn't seem to be a way for the double to take it's place.
> 
> This is a piece of my code for example:
> ![image](https://user-images.githubusercontent.com/25863930/109712128-eb24b500-7b9f-11eb-8a30-0205bcb72bbc.png)
> 
> How could I stub a method called this way? I could technically add a layer of abstraction by storing a reference to the global namespace and then replace that by the double when testing, but imo that would dirty the code as there is no apparent reason to add that layer besides compatibility for testing.
> 
> So for the core methods, if I understand correctly I could only stub them through a self made derived class?
> Since there is no known script location for core classes I could not think of any other way either.

There might be a very dirty way of me doing this. I'd basically take your script, remove the class_name, save it, create my own script which extends from your script and then give that new_script the class_name, at this point you could stub any of the methods you'd want. Afterwards I'd clean up and give the base script the class_name back.

I'm not 100% sure if this will work but if it did, do you think you'd be alright with that?

**Comment by ChocolatePinecone** [comment]
> > Oh, that's interesting about the static methods!
> > Though if the tested function calls the global method directly, there doesn't seem to be a way for the double to take it's place.
> > This is a piece of my code for example:
> > ![image](https://user-images.githubusercontent.com/25863930/109712128-eb24b500-7b9f-11eb-8a30-0205bcb72bbc.png)
> > How could I stub a method called this way? I could technically add a layer of abstraction by storing a reference to the global namespace and then replace that by the double when testing, but imo that would dirty the code as there is no apparent reason to add that layer besides compatibility for testing.
> > So for the core methods, if I understand correctly I could only stub them through a self made derived class?
> > Since there is no known script location for core classes I could not think of any other way either.
> 
> There might be a very dirty way of me doing this. I'd basically take your script, remove the class_name, save it, create my own script which extends from your script and then give that new_script the class_name, at this point you could stub any of the methods you'd want. Afterwards I'd clean up and give the base script the class_name back.
> 
> I'm not 100% sure if this will work but if it did, do you think you'd be alright with that?

I'm not sure I'm seeing how this would solve the GlobalFunctions.ShipParts.clone_part call. If you derive from my script calling it, you will only be able to stub the native functions to that class, right? You still won't be able to stub the Global static "clone_part" function.

**Comment by AlexDarigan** [comment]
I didn't realize there was another step involved. That's a fair point.

**Comment by AlexDarigan** [comment]
Closing this because I think it is to the point of where everything else around it should be tested and we just see how that fairs.

**Comment by AlexDarigan** [comment]
Reopening unresolved issue.

**Comment by AlexDarigan** [comment]
Reviewing this, I think this is practically impossible and is better solved by better design patterns (namely less globals, or at the very least a singleton where the instance could be swapped for a double).
