### ISSUE TITLE
Tags doesn't appear in the editor or can be modified in test tab

### ISSUE THREAD

**Issue by AnidemDex** [AlexDarigan/WAT#211]
**Using:**

Godot 3.3

---

I can't edit script tags within editor or in the test tab.

**Current tags:**
![image](https://user-images.githubusercontent.com/7025991/116834436-b626e580-ab83-11eb-916b-48cc5504c0ee.png)
**Tags in Tests tab:**
![image](https://user-images.githubusercontent.com/7025991/116834738-123e3980-ab85-11eb-81cf-4f35f7a4c4fb.png)

**Tests tab:**
![image](https://user-images.githubusercontent.com/7025991/116834651-ac51b200-ab84-11eb-82f2-cbb33bc661b0.png)
**Error that appear when edit tags with test tabs:**
![image](https://user-images.githubusercontent.com/7025991/116834672-c5f2f980-ab84-11eb-97a6-bebc4e7025a2.png)

**Comment by AlexDarigan** [comment]
You may need to restart the plugin for this to work.

**Comment by AnidemDex** [comment]
> You may need to restart the plugin for this to work.

Still the same issue when restarting Godot or the plugin.

**Comment by AlexDarigan** [comment]
Can't replicate this in 3.3

Has it changed for you recently? On top of that did you make sure none of the WAT tool scripts were open?

**Comment by AlexDarigan** [comment]
Were you using 5.0.0? It seems this was corrected in master (and now 5.0.1 release) so check that and get back to me.

**Comment by AnidemDex** [comment]
Sorry for not seeing this early, I'll give it a try and close it if everything works

**Comment by lukaskj** [comment]
Same here. 
Installed today from [Godot asset library](https://godotengine.org/asset-library/asset/495)

Godot 3.3

Reinstalled the plugin, restarted, Godot, clean project and "not clean" project. All with same error.

![image](https://user-images.githubusercontent.com/1936255/118748076-8e957580-b831-11eb-81ab-1b9e5e7e7645.png)

![image](https://user-images.githubusercontent.com/1936255/118747932-4fffbb00-b831-11eb-95c9-0d87b1bf7c62.png)

![image](https://user-images.githubusercontent.com/1936255/118747949-568e3280-b831-11eb-83ac-a44cd383a312.png)


I'm not using this tag feature yet, just happened to catch this error.
I'm first learning how to use the basics of this plugin.

**Comment by AlexDarigan** [comment]
Could you upload your project because I just seem incapable of reproducing this on my end? @lukaskj

**Comment by AlexDarigan** [comment]
This is a bad accessor, it keeps returning nothing. Popups have a problem with retaining junk data so I'll have to investigate further.

**Comment by lukaskj** [comment]
I just created a clean project to upload with this issue but it started working.
![image](https://user-images.githubusercontent.com/1936255/118911832-375cd700-b8fd-11eb-9ec9-27a98cce7eab.png)

Then I went back to the project that I took the previous comment screenshots and it worked as well.
![image](https://user-images.githubusercontent.com/1936255/118911970-6ecb8380-b8fd-11eb-8602-32ea76ad10c5.png)

I updated to 3.3.1 today before opening the projects. Maybe it was it?

**Comment by AnidemDex** [comment]
Is working now in the lastest version, sorry for letting this issue open

**Comment by AlexDarigan** [comment]
The latest release or the latest master? The master might be unstable.

**Comment by AnidemDex** [comment]
Lastest release atm (5.0.1)
