### ISSUE TITLE
Doubled scenes loose all changed properties

### ISSUE THREAD

**Issue by Jummit** [AlexDarigan/WAT#219]
In this code nodes get instanciated, but properties aren't set on the doubles:

https://github.com/AlexDarigan/WAT-GDScript/blob/f4ff6b9cfe29c5e11898e8dac6cdc04b4460e65f/addons/WAT/core/double/factory.gd#L25-L28

**Example**:
```gdscript
var director = direct.scene("res://some/scene.tscn")
var double = director.double()
# Prints the default value, even if it's changed in scene.tscn.
print(double.member)
```

**Comment by AlexDarigan** [comment]
For at the very least top-level scenes should have this sorted with this fix. https://github.com/AlexDarigan/WAT-GDScript/commit/1c6cde758d1f3a1af12cbc624fa11a831db7d8d9

**Comment by AlexDarigan** [comment]
We're resetting too many things. May have to add some default exclusions or a way to make sure the property isn't exported. (The current change is why scene director test is broken).

**Comment by AlexDarigan** [comment]
Seems 8199 is the bit number for user exported variables, so we'll just focus on those.

**Comment by AlexDarigan** [comment]
This has been solved for a while I think so I'm going close this until it pops up again.
