### ISSUE TITLE
C#'s Assert.IsEqual (and IsNotEqual) don't work with null

### ISSUE THREAD

**Issue by ace24713** [AlexDarigan/WAT#261]
Ran into this one in 5.0.1 release, but the relevant code doesn't seem different on master so it should still be an issue.

Problem is in [Equality.cs](https://github.com/AlexDarigan/WAT/blob/c9e3fb80fea6407c81ceae5655d9e953a0f952e8/addons/WAT/mono/assertions/Equality.cs#L13-L17) if a or b are null, you can't call `.GetType()` on a null object. Additionally if a is null, `a.Equals(b)` will similarly not work. I believe `object.Equals(a, b)` will work in it's place.

As a workaround, the Assert.IsType can check for null instead. But this only works if you're explicitly checking for null, and not in the case you're comparing two values that might be null.

**Comment by AlexDarigan** [comment]
If this doesn't work on Is/IsNotEqual, it should be considered that it doesn't work anywhere WAT uses GetType right? Have you checked it with other Assertions using get type?

**Comment by ace24713** [comment]
I haven't checked it out, but that sounds right to me. I only ran into this issue as my first intuition to assert a value wasn't null was to write `Assert.IsNotEquals(myvalue, null);` And while I haven't verified it, the gdscript versions of all these assertions look like they'd handle null just fine.

Also I just noticed that the gdscript assertions include a is_null/is_not_null that aren't present in C#.

**Comment by AlexDarigan** [comment]
Should be resolved by 04514423fd426c0863429dbfee4a057bb3f19c95

> Also I just noticed that the gdscript assertions include a is_null/is_not_null that aren't present in C#.

It is a weird issue in Godot C# and how it manages memory.
