### ISSUE TITLE
Documentation on ReadTheDocs returns 404

### ISSUE THREAD

**Issue by duchainer** [AlexDarigan/WAT#288]
Is it only on my side?

**Comment by AlexDarigan** [comment]
All of the documentation has been merged into the README here along with comprehensively commented examples in the res://tests/examples folder.

**Comment by duchainer** [comment]
Thanks for the precision, I was confused since the links menu of the WAT GUI was still taking me to the old ReadTheDocs. 
I must have missed an update. :)

Is there a specific reason why the ReadTheDocs was dropped in place of a big README, other than it being easier to maintain?

**Comment by duchainer** [comment]
Oh, also the link [from the github wiki ](https://github.com/AlexDarigan/WAT/wiki/Documentation) is still redirecting to [the removed ReadTheDocs](https://wat.readthedocs.io/en/latest/index.html).

**Comment by AlexDarigan** [comment]
> 
> 
> Thanks for the precision, I was confused since the links menu of the WAT GUI was still taking me to the old ReadTheDocs.
> I must have missed an update. :)
> 
> Is there a specific reason why the ReadTheDocs was dropped in place of a big README, other than it being easier to maintain?

The links were removed in the new livewire release (or at least should have been).

Beyond being just easier to maintain, I felt that I kept writing a lot for what is really a simple code example and they were just too big for the amount of info I was trying to convey.
