### ISSUE TITLE
Using WAT in Godot 3.3.3

### ISSUE THREAD

**Issue by miquelramirez** [AlexDarigan/WAT#289]
Hello,

I was using - successfully - WAT on Godot 3.3.3, and after adding a new unit test to my `tests` folder, I am getting this error when I try to run the tests:

``` 
D:\Sandboxes\Godot_v3.3.3-stable_win64.exe .\addons\WAT\cli.tscn run=all
ERROR: Could not create directory: res://logs
   At: core/os/dir_access.cpp:184
Godot Engine v3.3.3.stable.official.b973f997f - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
OpenGL ES Batching: ON
 
ERROR: call: Invalid Argument
   At: modules/gdscript/gdscript_functions.cpp:803

Process finished with exit code 0
```

How can I diagnose the causes for this? The User Interface is unresponsive (e.g. I click on the "run tests" buttons and nothing happens). The main scene of the project, using the classes in the tests, is being run by the editor without issues.

**Comment by AlexDarigan** [comment]
What version of WAT are you using (newest release?)

Go to addons/WAT, click gui, run that as a scene with F6, then the debugger will trigger for more info.

**Comment by miquelramirez** [comment]
Cheers @AlexDarigan for the quick response. Here's the version as reported by the editor user interface (`5`)

![image](https://user-images.githubusercontent.com/444457/132115366-c8b8ed05-8c1e-4e2a-b64f-abc7efdef801.png)

> Go to addons/WAT, click gui, run that as a scene with F6, then the debugger will trigger for more info.

Interesting - if I run the `gui` scene directly WAT runs my test without (unexpected) problems.

**Comment by AlexDarigan** [comment]
Tests refer to Scripts in the command line. Not the total test methods. I should probably add that clarification.

**Comment by AlexDarigan** [comment]
Your currently installed version is 6 right?

**Comment by miquelramirez** [comment]
Hi there,


> Your currently installed version is 6 right?

Yep.

I did a clean reinstall - turn off plugin, delete local files under `addons`, shut down editor, re-download, re-install. reboot editor - just in case. And now it works.

> Tests refer to Scripts in the command line. Not the total test methods. I should probably add that clarification.

Cool, that was a bit confusing :) Now I realise that the tab that opens when the GUI runs the tests reads "( 2 / 2 ) res://tests".

Thanks very much for your help.

**Comment by AlexDarigan** [comment]
It seems the old files weren't overwritten properly. This was an issue with the root directory where if it was root it would only run all tests in subdirectories but not its own top level tests due to a bad if statement on my part.

Seems like a clean install is the only way to really fix this issue.

**Comment by miquelramirez** [comment]
Cheers @AlexDarigan, I appreciate the further comments. And thank you very much for coming up with `WAT`, an essential tool!
