### ISSUE TITLE
Strange Errors When Running From Command Line

### ISSUE THREAD

**Issue by knightofiam** [AlexDarigan/WAT#291]
When running tests from the command line, it runs the tests just fine, but there are some strange errors afterward:

```
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2132.
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:450.
```

Is there a workaround or fix for this?

**Comment by AlexDarigan** [comment]
It is a memory leak. It isn't actually entirely possible to clear up in C#.

It might take a while to track down all of the leaks currently but it isn't anything worth worrying too much about.

**Comment by rsmz** [comment]
I see these too and suppress them with `test.sh 2> /dev/null`. Would I ever miss any important messages from WAT by redirecting stderr as a workaround, or is there a more graceful way to silence them?
