### ISSUE TITLE
Results Subdirectory Not Respected

### ISSUE THREAD

**Issue by knightofiam** [AlexDarigan/WAT#292]
I set `Results Directory` to `res://tests/results` in the Editor, saved, ran the tests, and results only appear in res://tests/results.xml. I tried allowing WAT to create the results subdirectory, which didn't work, so I created it myself, and it still didn't work. I tried restarting the editor, running the tests both from the editor and from the command line, deleting results.xml from the wrong location, changing the setting multiple times, no dice.

How can we use a subdirectory for the results?

I should probably mention that a subdirectory worked just fine for `Test Metadata Directory`, at `res://tests/metadata`.

**Comment by AlexDarigan** [comment]
Typo in this where else should be path = results_directory() 

https://github.com/AlexDarigan/WAT/blob/main/addons/WAT/io/junit_xml.gd

**Comment by AlexDarigan** [comment]
Should be resolved by 3a6e746523b658991e83289f56bd34afc196ee67

**Comment by knightofiam** [comment]
@AlexDarigan Unfortunately, I don't think this is fixed. I just now got a chance to test your fix and the results directory is correctly updated in `project.godot` after changing it via the editor's project settings, but when running the tests, it still puts `results.xml` in `res://tests`, not `res://tests/results`, completely disregarding the setting.

**Comment by knightofiam** [comment]
Strange, it seems to be working now. I think the only thing I did was to close and re-open the Godot editor.  I'm also not sure if it's supposed to create the folder for you if it doesn't exist? I thought I tried it both ways.

**Comment by knightofiam** [comment]
No, I think I figured out what changed. This was automatically added to my project's `csproj`:

```
<ItemGroup>
<Folder Include="tests\results" />
</ItemGroup>
```

Is that really necessary for this to work? I'd rather not have it there. The `metadata` and `logs` directories aren't added there and work just fine. It also has a Windows-style backslash, which I loathe. The plot thickens...

**Comment by knightofiam** [comment]
Very strange. I removed the `csproj` entry and ran the tests both from Rider & the Godot editor, and it seems to be working just fine.

**Comment by AlexDarigan** [comment]
May have just required a fresh build. Alternatively maybe using a static function is a bad idea for this.

**Comment by AlexDarigan** [comment]
Seems this was resolved?
