### ISSUE TITLE
Modifying a test class or method causes the test runner to fail

### ISSUE THREAD

**Issue by olestourko** [AlexDarigan/WAT#295]
Godot 3.3.3 stable
C# (Mono)
WAT Version 6

When I run tests through the "Test" tabs after modifying a test class' name, a test method name, or ad a new test method, the test runner fails. I'm writing C# tests and using "Build" in Godot after my changes.

This only appears to be happening if I had run tests before making changes - maybe WAT is caching class/method definitions? It appears that the new class/method names aren't picked up in the test runner's dropdowns. There isn't anything in the Output tab and no dropdowns under the failure in the Test tab.

![Screenshot_2021-09-15_18-13-39](https://user-images.githubusercontent.com/3958783/133516913-c42adef9-1894-423d-a333-0fca52b501df.png)

If I reload the project the new tests get picked up and it works again. Toggling the plugin in projects settings works too.

**Comment by AlexDarigan** [comment]
Might be a cache problem alright.

**Comment by AlexDarigan** [comment]
Are you using an external editor? Maybe the filesystem dock signals that WAT uses aren't being sent.

**Comment by olestourko** [comment]
I got around it by skipping the file system check here: https://github.com/AlexDarigan/WAT/blob/3a6e746523b658991e83289f56bd34afc196ee67/addons/WAT/ui/gui.gd#L64

Maybe there's a way of detecting changes to C#-based scripts? Just picked up Godot so very fresh to this all

**Comment by olestourko** [comment]
> Are you using an external editor? Maybe the filesystem dock signals that WAT uses aren't being sent.

Yes, VSCode on Ubuntu 20.04

**Comment by AlexDarigan** [comment]
If you save the file, a "resource_saved" signal will be emitted which will trigger an update of the system.

This might be a VSCode issue. Worth trying to see if the changes get picked up when you change and save from the editor.

**Comment by olestourko** [comment]
Yup, WAT detects change made through the builtin editor

**Comment by AlexDarigan** [comment]
Oh I have an idea. The filedock signals will probably trigger from an external editor but this resource_saved one won't because it is a plugin signal and that's the one we care about. 

I think having the system auto-update might be the best for now until I can figure this out.

**Comment by AlexDarigan** [comment]
Maybe a launch.json for WAT specifically.

**Comment by olestourko** [comment]
I'm very new to Godot so I'm not sure what all of that means :sweat_smile: If its useful at all, the builtin editor is picking up changes I make externally in VSCode.

I actually did try setting up a `launch.json` for WAT but the current version of Godot is ignore the args passed to it, so it wouldn't take the WAT cli args: 
https://github.com/godotengine/godot-csharp-vscode/issues/19

**Comment by olestourko** [comment]
In the meantime just keeping my hack to skip the `_filesystem.change` check is enough for me, personally. If this ends up being a difficult thing to figure out, perhaps a setting on the extension to optionally skip the check for external editor users could be a compromise?

**Comment by AlexDarigan** [comment]
A reminder to myself: Could experiment different files saved signals from other sources with a check that breaks if filesystem was updated.

**Comment by olestourko** [comment]
`SriptEditor` can receive signals about changes to _active_ scripts, but I can't find a way to receive signals about inactive ones. Here's a simple draft PR for a setting to disable caching: https://github.com/AlexDarigan/WAT/pull/296

**Comment by AlexDarigan** [comment]
Check if this works c6bb81ab803e333a11352ee207ba904ed72b0030

**Comment by AlexDarigan** [comment]
Seems this issue has been resolved.
