### ISSUE TITLE
director does not free memory and overflows during testing.

### ISSUE THREAD

**Issue by Valeryn4** [AlexDarigan/WAT#297]
director does not free memory and overflows during testing.

I run a test to check that all scenes are valid. Each new test run does not release memory and causes a leak.
_register - never calls clear ()
_register.clear () - does not clear test_directors = {} and does not destroy Director objects. Director continues to contain heavy structures and a null pointer "object"
The collection continues to contain empty objects.
_register is Object and never frees.

![image](https://user-images.githubusercontent.com/12483173/134653672-3570fa19-3816-4870-9690-d9a1f51fd377.png)

I have to break encapsulation.
```gdscript
	_registry.clear()
	for director in _registry.test_directors.values() :
		director.free()
	_registry.test_directors.clear() 
```

**Comment by AlexDarigan** [comment]
Ah okay. This is a poor assumption on my part where clear should be be called when the Test Class is finished but the option should exist to clear it after each method as well. I could probably add an enum setting like CLEAR_IN_POST, CLEAR_IN_END when doubling items to solve this. Maybe with a default in project settings.

**Comment by Valeryn4** [comment]
What can I do now to make it work now?

**Comment by AlexDarigan** [comment]
You could add a check around line 48 here for "if hook = "post" and then call clear on the director.

**Comment by AlexDarigan** [comment]
Added a clear() method to director so you can call it at the end of a post hook (or even during a test if you want for whatever reason)? See f04cdc48f07521c8b774e7f4f4bf3051c55dd0f7

Closing this but feel free to comment if issues persists.
