### ISSUE TITLE
Parameterized tests aren't run correctly

### ISSUE THREAD

**Issue by bmolyneaux** [AlexDarigan/WAT#298]
Godot version 3.3.3.stable

There are a couple of related issues with parameterized tests. The below source code demonstrates both issues.

The number of parameterized test cases run is only as many as there are test methods in the script. For example if `test_parameterized()` has 3 test cases, but only 2 test methods are defined for the script (`test_parameterized()`  and `test_print_and_fail()`), then only the first 2 cases will be run.

Running parameterized tests causes other tests to not run. Since `test_parameterized()` has multiple test cases, `test_print_and_fail()` is not run.

```
func test_print_and_fail():
	print("Running the print and fail test")
	asserts.is_true(false)

func test_parameterized():
	parameters([
		["id"],
		[0],
		[1],
		[2],
	])
	
	print("Running test ", p["id"])
	
	asserts.is_true(true)
```

Expected result: 3/4 tests passed
Expected output:
```
Running the print and fail test
Running test 0
Running test 1
Running test 2
```

Actual result: 2/2 tests passed
Actual output:
```
Running test 0
Running test 1
```

**Comment by AlexDarigan** [comment]
I believe this has been resolved in master.
