### ISSUE TITLE
C# - changes to tests require a restart to be detected

### ISSUE THREAD

**Issue by derkork** [AlexDarigan/WAT#299]
Godot 3.3.3 Mono on Windows 10.

I have installed WAT into my project. The plugin is activated and I can see the Tests tab at the bottom of the editor. Now I add a test to my test directory. However this test is not detected even when I do a build of the project. It is only detected when I close the Godot editor and reopen it. Similarly if I just add a test to an existing class, it this change is also not detected. Again I need to restart the Godot editor for the changes to be detected.

**Comment by AlexDarigan** [comment]
Might be related to this https://github.com/AlexDarigan/WAT/issues/295

Are you using an external editor?

**Comment by AlexDarigan** [comment]
Check if this works c6bb81ab803e333a11352ee207ba904ed72b0030

**Comment by derkork** [comment]
> Might be related to this #295
> 
> Are you using an external editor?

Yes, I'm using Rider for editing C# scripts.

**Comment by ashelleyPurdue** [comment]
I was having the same problem as @derkork .  I applied the changes from `c6bb81a`, as suggested, but now _none_ of my tests are being detected, even after a reload.  Even worse: my tests _still_ aren't detected even when I undo that change.

**Comment by pracplayopen** [comment]
also having this problem.

tests were not detected until after restarting project.
external editor (vscode) is being used.
this is with godot-mono-3.3.3
installed WAT (WAT-mono) via asset library, as recommended.

would imagine most people writing tests would be using external editors (as godot's c# editor doesn't support intellisense).

also i can't verify that tests are actually running.
all my tests fail, even empty ones.
even a hello world message won't print from test (tho perhaps it's not sent to output window, it's somewhere else?)

i do also see an error in the output window from WAT:

```
Godot Engine v3.3.3.stable.mono.official (c) 2007-2021 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- GDScript language server started ---
 res://addons/WAT/filesystem/validator.gd:16 - Invalid call. Nonexistent function 'new' in base 'CSharpScript'.
Switch Scene Tab
Connection Taken
```

am happy to collect more information if that would help.

**Comment by pracplayopen** [comment]
ok so after looking at other similiar issues, did following : 

* modified filesystem/_filesystem.gd in WAT's addons folder, per: https://github.com/AlexDarigan/WAT/commit/c6bb81ab803e333a11352ee207ba904ed72b0030
* restarted editor
* after doing so, changes in external editor are picked up in godot/WAT whenever you re-build
* so it seems now no restarting of editor is needed w/this change

thanks again @AlexDarigan.  +1 this patch to go into version being installed via asset library.

**Comment by nightblade9** [comment]
I'm still seeing this behaviour in 6.0.1.

I'm also seeing an interesting case where changing test contents and re-running shows the old test results - even though the test status should change (from pass to fail or vice-versa). Restarting Godot fixes the problem.
