### ISSUE TITLE
"Select Tests" dropdown not populating post 1st run, and not all tests showing up.

### ISSUE THREAD

**Issue by TheDuckCow** [AlexDarigan/WAT#300]
I'm running into a couple issues which are likely intertwined with the current v6.0.0 version (godot v3.3.3, OSX using gdscript). I also tried using master with the same result. Using a prior release works fine however (not sure which version it's from, at least a few months old), other than, I'm trying to use some new features not available in the old version to do with watching signals.

See the videos linked below, my observations being:

- The "Select Tests" [fails to populate](https://drive.google.com/file/d/1kT2pMt9lgHG4Liu6o8FTmygL1jOFtWSi/view?usp=sharing) after running all or any tests the first time; I have to restart godot for this dropdown to work again.
- For some reason, [one of my tests](https://drive.google.com/file/d/1EO-dBQiGvay5KQC-H9S7hFqUEhS_4_1l/view?usp=sharing) (from the network folder) doesn't show in this dropdown or run with run all. In the prior version of WAT however this does run. I do see that when I open my project there are some errors related to the module it imports and an autolod it utilizes, however I don't think it's an issue with that autolod itself because if I copy over the older version of WAT it runs fine. I wonder if the 6.0 release tries to run something right on startup when it shouldn't yet?
  - Ah but now, suddenly, pressing rerun all and [it shows that test[(https://user-images.githubusercontent.com/2958461/135744203-38ad3545-a5ca-47b5-b730-40fe0e2bc1f7.png) (that test failing is expected); dropdown for Select Tests still not populating in this state.

Tried sharing what I thought would be useful, but let me know if there's anything else I can provide.

**Comment by AlexDarigan** [comment]
The first issue is related to https://github.com/AlexDarigan/WAT/issues/299#issuecomment-932594084 and https://github.com/AlexDarigan/WAT/issues/295#issuecomment-926218150. I think right now I'll just have to auto update C# tests until I have time for a better solution.

I'm not sure what's going on with the second issue.

**Comment by AlexDarigan** [comment]
For the first issue see this fix c6bb81ab803e333a11352ee207ba904ed72b0030

**Comment by AlexDarigan** [comment]
I believe this should have been resolved.

**Comment by TheDuckCow** [comment]
Thank you! I'll try later and comment back if anything still seems up.
