### ISSUE TITLE
preload() interferes with loading of test scripts during Debug tests (GUI)

### ISSUE THREAD

**Issue by RailKill** [AlexDarigan/WAT#302]
#### Issue description
**WAT Version:** 6.0.0 (GDScript)
**Godot Version:** 3.3.3 (also tested on 3.3.4)
**OS:** Windows 10

In previous versions of WAT, we used to be able to preload resources in the test script. In WAT 6.0.0, this breaks Debug All Tests (GUI) and produces an infinite loop in the TestRunner scene. I'm not sure if ```preload()``` should not be used in testing, but it used to work in WAT 4.0. Plus, it also works when running without the debugger, so there is an inconsistent behavior here that should be seen as a bug.

#### Steps to reproduce the issue
1.  Create a test script that has preload() anywhere, for example:
    ```
    extends WAT.Test

    var player = preload("res://assets/player.tscn")
    ```
2. Using the WAT GUI, run all tests with debugger.
    ![debug-all](https://user-images.githubusercontent.com/11093103/136563345-e9ac0fc8-1771-4e3f-aa2d-81ebab3c3d61.jpg)

#### What's the expected result?
The TestRunner scene should run all tests, close when complete, and display the test results.

#### What's the actual result?
The TestRunner scene gets stuck in an infinite loop. To be precise, it gets stuck trying to load the test script in line 16 of [test_controller.gd](https://github.com/AlexDarigan/WAT/blob/main/addons/WAT/runner/test_controller.gd)

#### Workaround
Instead of using ```preload()```, we can use ```load()``` ***inside*** one of the test methods or in ```pre()``` and such. If ```load()``` is used at the top level such as at the beginning of the test script, it will produce the same problem.

**Comment by AlexDarigan** [comment]
Is this still an issue? I can't replicate it. Any chance your player scene is recursive to some other object?

**Comment by RailKill** [comment]
It's possible. I'll close this issue since it doesn't seem like it has anything to do with WAT anyway, especially after having delved into the code.

**Comment by AlexDarigan** [comment]
Thanks.

**Comment by AlexDarigan** [comment]
Reopening unresolved issue. Maybe documentation or something.

**Comment by AlexDarigan** [comment]
This doesn't seem to exist in 3.5 as far as I can tell.
