### ISSUE TITLE
Run Single Test Class

### ISSUE THREAD

**Issue by knightofiam** [AlexDarigan/WAT#304]
Is there a way to run a single test class?

I tried on the command line with:

```
Run Script

// Where X is the absolute path of the script you want to run
godot addons/WAT/cli.tscn run=script+X
````

but I get:

```
SCRIPT ERROR: _parse: Invalid get index '[redacted]/tests/MotionsTest.cs' (on base: 'Dictionary').
   At: res://addons/WAT/ui/cli.gd:39.
```

so I think I'm ~abusing~ misusing the above feature. ;-)

The ability to test a single class is useful while writing tests for that class when other classes' tests take a while to run. The only workaround I can think of would be to comment out the other files, or all of the [test] annotations, which is kind of a frustrating workflow. Or write some kind of flag into each test - again, kind of an inefficient and bug-prone workflow.

**Comment by knightofiam** [comment]
@RailKill Thank you! That syntax worked for me to run a single class. @AlexDarigan My test folder is internal to the Godot Project Folder. Is there README documentation about using the `res://` syntax on the command line? I only saw that it said "absolute path". I don't see `res://` as absolute at all. It's relative to the Godot project directory.

**Comment by rsmz** [comment]
I was also misled about using an absolute path.  In addition, I used the print suggested by @RailKill and I don't understand why the printed paths have double slashes after my tests directory like "res://tests//subdir:[Reference:1218]".  My tests will run with the argument like "run=script+res://tests//subdir/stuff.gd".  I'm running from iTerm on macOS GNU bash version 3.2.57(1)-release (x86_64-apple-darwin20)

**Comment by AlexDarigan** [comment]
It is common to refer to res:// as absolute within the context of Godot. You can see this in their documentation about preloading/loading files. However I can see where the confusion is coming from.

**Comment by AlexDarigan** [comment]
Clarified this in the README.md ed496393f7ac12ed054c6541dcfc8d9024860eef

**Comment by knightofiam** [comment]
@AlexDarigan Is there a reason you [removed](https://github.com/AlexDarigan/WAT/commit/c82496a33d4541c00f9caa77e66d30cd9b1ee215) the clarification? I struggled with this again today after forgetting to use the ```res://``` syntax. I can't be the only one.

**Comment by AlexDarigan** [comment]
My bad. I'll fix that right now.

**Comment by knightofiam** [comment]
@AlexDarigan Thanks! Although don't you think it say ```godot addons/WAT/cli.tscn run=script+res://X```, rather than ```res://script+X```? The former is what works for me anyway. I think a ```tests``` directory is pretty common, maybe it would be less confusing to provide an example, such as ```run=script+res://tests/MyTest.cs```, where ```tests``` subdir is in the project root.
