### ISSUE TITLE
describe() does not change test name in GUI results

### ISSUE THREAD

**Issue by RailKill** [AlexDarigan/WAT#306]
#### Issue description
**WAT Version:** 6.0.0 (GDScript)
**Godot Version:** 3.3.4
**OS:** Windows 10

When running tests in GUI, the resulting test names will always grab from the test method name. ```describe()``` has no effect. 

#### Steps to reproduce the issue
1. Run [tests/examples/gdscript/example.test.gd](https://github.com/AlexDarigan/WAT/blob/main/tests/examples/gdscript/example.test.gd) in the editor (GUI).
  *Note: the test_simple_example() method uses ```describe("My Example Test Method")```*

#### What's the expected result?
In the test results, the name for test_simple_example() should be displayed as "My Example Test Method"

#### What's the actual result?
The name is displayed as "simple example"

![describe-not](https://user-images.githubusercontent.com/11093103/137212169-cefbdcf6-6279-430f-916d-495852257078.jpg)

#### Additional details
This issue only occurs for GUI. The name is shown correctly in results.xml and in CLI.

**Comment by AlexDarigan** [comment]
Seems your PR has resolved this.
