### ISSUE TITLE
double() fails if script director uses method with user-defined default arguments

### ISSUE THREAD

**Issue by RailKill** [AlexDarigan/WAT#308]
**Issue description**

**WAT Version:** 6.0.0
**Godot Version:** 3.3.4
**OS:** Windows 10

**Steps to reproduce the issue**
1. Edit [examples/doubles/calculator.gd](https://github.com/AlexDarigan/WAT/blob/main/examples/doubles/calculator.gd) and put a default value in one of the arguments of the add() method as such:
  ```
  func add(a, b = 5) -> int:
	return a + b
  ```
2. Run the method director tests.

**What's the expected result?**
Tests should pass.

**What's the actual result?**
```
 built-in:7 - Parse Error: The function signature doesn't match the parent. Parent signature is: "int add(Variant, Variant=default)".
 modules/gdscript/gdscript.cpp:585 - Method failed. Returning: ERR_PARSE_ERROR
 Error calling method from 'callv': 'GDScript::new': Method not found..
 res://addons/WAT/double/script_director.gd:138 - Invalid get index 'WATRegistry' (on base: 'Nil').
```

**Comment by AlexDarigan** [comment]
I have a lot of plans for 4.0 but want to focus issues on 3.X.X for now so I'm going to close this and marked it as a benched so we know to come back to it.

**Comment by AlexDarigan** [comment]
Reopening unresolved issue.

A note: Considering writing test doubles as separate plugin that can be used in conjunction with WAT rather than a core feature of WAT which should hypothetically allow for a more robust Test Double system.

**Comment by AlexDarigan** [comment]
I've been thinking about this. A large problem was that previously it would have been hard to find which script this method existed in, which means the script we would be parsing for the defaults might not have the function at all. However thanks to the event of get_script_method_list(), it seems we'll be able to loop to the correct script to double the method. then do a source.split("\n") or some form of regex(func name(*)) and then parse the paranthesis. We'd likely focus on doubling primitive defaults for now though.

**Comment by AlexDarigan** [comment]
In ScriptDirector, we have the set methods function which is already handling the built in defaults (since these ones actually work correctly) 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/47497501/235451832-6310985c-22b5-460d-ab2c-f33ed3290d26.png">

My idea here is, if it isn't nested or built-in, we use a different default args by looping through the source code until we find the function in quest. Split the source code, and then attempt our best to extract the args, and types.

**Comment by AlexDarigan** [comment]
Finally resolved by https://github.com/AlexDarigan/WAT/pull/373

Inner Classes are still limited but that cost-value ratio just isn't worth it for now, so optional keywords and retvals are kept in.
