### ISSUE TITLE
"Nonexistent function 'new' in base  'CSharpScript'" when using Generic class as parent for tests

### ISSUE THREAD

**Issue by Fro-Z** [AlexDarigan/WAT#309]
Hello,
I have a C# generic class that serves as a test fixture around a Godot scene. Its goal is to load and unload Godot scenes so I don't have to do it manually in every single test. Every time I start Godot there is the following error:

`res://addons/WAT/filesystem/validator.gd:17` : `SCRIPT ERROR: _is_valid_csharp: Invalid call. Nonexistent function 'new' in base
 'CSharpScript'.`
 
Thankfully, the error does not block me in any way. 

The offending C# class:
```c#
    [Pre(nameof(SetUp))]
    [Post(nameof(TearDown))]
    //! Fixture that creates and destroys a scene for the test
    public class SceneFixture<TSceneType> : WAT.Test where TSceneType:Godot.Node
    {
        private PackedScene _packedScene;

        //! Godot scene (node) of this test
        protected TSceneType Scene => _scene;
        private TSceneType _scene;

        public SceneFixture(PackedScene packedScene)
        {
            this._packedScene = packedScene;
        }
        
        //! Called when the test fixture is created
        public virtual void SetUp()
        {
            _scene = _packedScene.Instance<TSceneType>();
            AddChild(_scene);
        }

        //! Called when the test fixture is destroyed
        public virtual void TearDown()
        {
            if(IsInstanceValid(_scene) && !_scene.IsQueuedForDeletion())
                _scene.QueueFree();
        }
    }
```

**Comment by pracplayopen** [comment]
also receive this message when NOT using generics:

```
res://addons/WAT/filesystem/validator.gd:16 - Invalid call. Nonexistent function 'new' in base 'CSharpScript'.

```

**Comment by pracplayopen** [comment]
will note see this issue w/out using generics and with only class names that match filenames.

however like the original poster, this error doesn't seem to block anything or cause a side effect.

if nothing else you may want to just change to a warning rather than an all-caps error, since it doesn't seem to need immediate fixing.

**Comment by AlexDarigan** [comment]
> if nothing else you may want to just change to a warning rather than an all-caps error, since it doesn't seem to need immediate fixing.

The error is from Godot. I don't have control over its output.

**Comment by pracplayopen** [comment]
ok.  another way to say it might be that whatever you are checking in validator that generates this error, the check doesn't seem to be significant in terms of using WAT.  so perhaps it's superfluous?

for anyone else wanting to help out here, [this is file in question](https://github.com/AlexDarigan/WAT/blob/main/addons/WAT/filesystem/validator.gd)

and here is the bit of code it's complaining about:

> static func _is_valid_csharp(p: String) -> bool:
	# TODO: This requires extra checking for invalid or uncompiled csharp scripts
	# Any errors about no method or new function new found exists here
	if p.ends_with(".cs") and not "addons/WAT" in p and load(p).has_method("new"):
		var test = load(p).new()   # <--  INVALID CALL ERROR
		if test.get("IS_WAT_TEST"):
			test.free()
			return true
		else:
			test.free()
			return false
	return false

don't see anything that stands out as a problem but not gdscript expert here.

**Comment by AlexDarigan** [comment]
@Fro-Z This should be resolved in main.
