### ISSUE TITLE
V6.0.0 is missing its `LICENSE` file

### ISSUE THREAD

**Issue by Jayman2000** [AlexDarigan/WAT#310]
[According to the Godot’s Asset Library requirements,](https://docs.godotengine.org/en/stable/tutorials/assetlib/uploading_to_assetlib.html#requirements)

> The repo MUST have a license file, called either "LICENSE" or "LICENSE.md".

WAT does technically meet this requirement, but [both](https://godotengine.org/asset-library/asset/495) [versions](https://godotengine.org/asset-library/asset/948) in the asset library are missing the `LICENSE` file. I don’t think that WAT breaks the letter of that rule, but I feel like it breaks the spirit of it. Plus, the license itself says

> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

Including the license would make it easier to follow that part of the license. Hopefully, making it easier will increase the chances that people follow that part of the license.

**Comment by AlexDarigan** [comment]
Resolved by b60a6129d0e72bf0a24699b4bfacb60a701ff907
