### ISSUE TITLE
How to print line number of failure?

### ISSUE THREAD

**Issue by rsmz** [AlexDarigan/WAT#311]
I have thousands of tests and when one fails, it is very inefficient to find where it occurred using a manual binary search of commenting out code.  I tried passing in the stack as a context like `asserts.is_equal( 1, 0, str(get_stack()) )`, but the stack appears as an empty list `[]`. Why? What is another way to get test failures to show the assertion line number?

This is the output of a simple gdscript `prints( str(get_stack()) )`
[{function:_ready, line:65, source:res://Node2D.gd}]

**Comment by AlexDarigan** [comment]
If you're using this in the Editor, then you can go the left side of the failing function in the results display and click the little "f" which will open your script editor to the line of the failing function.

I should probably add an output like this to the CLI and other contexts where the goto function option doesn't work.

**Comment by AlexDarigan** [comment]
Reopening this. Should be able to add a get_stack() call when running the game context.

**Comment by AlexDarigan** [comment]
Implemented in ffe0b73d97d887521b926ef4989ceade13d61436

![image](https://user-images.githubusercontent.com/47497501/233871624-6baa8ee9-2013-4b70-b949-b928dc2c1d06.png)

You'll need to pass in -d after the executable to trigger the debugger (which is how we get the stack trace)

I'll expand on CLI output later.
