### ISSUE TITLE
Test folder scans - Unexpected behaviors

### ISSUE THREAD

**Issue by belug23** [AlexDarigan/WAT#313]
I've been trying the version 6.0.0 GDScript version in Godot 3.4

Since it's the first time I try the plugin, I don't know if it was working properly in 3.3

**Duplicating Tests script:**
When you duplicate a script from the test folder, the GUI doesn't refresh the list of scripts to run, run all doesn't run the new script.

**Creating a new script:**
While creating a new script in the tests' folder, the list of tests to run is refreshed, but the `Select Tests` menu is broken, and I need to reload the project to be able to select it again. But the run all script now run the new script, and it also runs tests that were created via duplicate.

Don't hesitate to ask questions if you need more info.

**Update:**
I've tested the duplicate bug with the mono version of the plugin and it working properly, but the menu is still broken.

System:
OS: Linux Pop!OS 20.04
Godot: 3.4.stable.official
WAT: 6.0.0 release for GDScript
Tests: I used the basic and yield example since I'm trying the framework for the first time.

**Comment by AlexDarigan** [comment]
``` When you duplicate a script from the test folder, the GUI doesn't refresh the list of scripts to run, run all doesn't run the new script.```

Due to the way the editor signals work, you will need to go into the script,changer something and then save it so that the "resource_saved" signal triggers.

**Comment by AlexDarigan** [comment]
> I've been trying the version 6.0.0 GDScript version in Godot 3.4
> 
> Since it's the first time I try the plugin, I don't know if it was working properly in 3.3
> 
> **Duplicating Tests script:** When you duplicate a script from the test folder, the GUI doesn't refresh the list of scripts to run, run all doesn't run the new script.
> 

Due to the way the editor signals work, you will need to go into the script,changer something and then save it so that the "resource_saved" signal triggers.

**Comment by AlexDarigan** [comment]
Closing this until it becomes an issue again.
