### ISSUE TITLE
Running tests doesn't work after previous run crashed and was stopped using F8

### ISSUE THREAD

**Issue by Jummit** [AlexDarigan/WAT#316]
If there was an error/crash while running the tests and the debugging process is stopped using F8, the clock still runs but WAT is broken and further runs just open an empty window.

The only reliable fix is to restart Godot, which is tedious as this happens frequently.

**Comment by AlexDarigan** [comment]
Please check if this was resolved from commit 790b30094931b5da1d6913c377174da12d0c3908

**Comment by Jummit** [comment]
Seems like the issue was resolved.
