### ISSUE TITLE
watch(...) without signal name

### ISSUE THREAD

**Issue by nightblade9** [AlexDarigan/WAT#325]
I'm migrating some tests over from GUT. In GUT, you only specify that you're watching an object:

```gdscript
var player = ...
watch_signals(player)
...
assert.signal_emitted(player, "moved")
```

In WAT, it's a bit more boilerplate: I need to specify the signal name both when calling `watch`, and also when calling the appropriate `asserts`.

Is it possible to simplify this to something more like GUT, where I don't need to pass in a signal name to `watch`? This is particularly useful if I'm testing something with multiple signals (emitted or not emitted) under test.

**Comment by AlexDarigan** [comment]
This isn't impossible to do but it is a pretty significant amount of work so I'll keep note of it for future versions.

**Comment by AlexDarigan** [comment]
watch_all(obj) / unwatch_all(obj) added in ccf9cf95b5252537de9d3da09518036f73acdd5d
