### ISSUE TITLE
Tests in namespaces don't run

### ISSUE THREAD

**Issue by nightblade9** [AlexDarigan/WAT#328]
I like to organize my tests to match my production code, and to use namespaces.

This test class works:

```
public class TestWatWorks : WAT.Test {
  [Test] public void TestMathWorks() {
    Assert.IsEqual(2 + 3, 5, "math broke");
  } 
}
```

Wrapping the entire class in `namespace Foo.Bar.Tests { ... }` doesn't - WAT doesn't find or run the test, I get `No tests found. Terminating run.`

**Comment by AlexDarigan** [comment]
This seems to work in master/the latest release for me. Are you using 6.0.1?

**Comment by nightblade9** [comment]
Not sure. `plugin.cfg` says `version="6"`, I think it's 6.0.0, I installed it from the assetlib a few hours ago.

**Comment by AlexDarigan** [comment]
Yeah. I'm bad at updating those. The assetlib is likely still taking a moment to be updated. Try the mono release from here https://github.com/AlexDarigan/WAT/releases/tag/v6.0.1-Mono

**Comment by nightblade9** [comment]
Is it possible you can update the assetlib instead?

**Comment by AlexDarigan** [comment]
> Is it possible you can update the assetlib instead?

It takes a while because they need to approve it first.

**Comment by AlexDarigan** [comment]
No problems reported any further here so closing this until further notice.

**Comment by AlexDarigan** [comment]
Reopening unresolved issue.
