### ISSUE TITLE
WAT 6.0.1 release throws error when running tests with `gui.tscn` in standalone mode.

### ISSUE THREAD

**Issue by Atlinx** [AlexDarigan/WAT#344]
The release zip files of WAT 6.0.1 has the following lines in `gui.gd`:
```GDScript
func _on_test_run_finished(results: Array) -> void:
	_plugin.get_editor_interface().stop_playing_scene() # Check if this works exported
	Summary.summarize(results)
	JUnitXML.write(results, Settings, Summary.time_taken)
	_filesystem.failed.update(results)
```

This line is causing an error when running in standalone mode, because _plugin doesn't exist in the standalone mode:
```GDScript
_plugin.get_editor_interface().stop_playing_scene() # Check if this works exported
```

The fix is to either make a null check or to remove the line altogether. I'm not really sure why that line is there, since `stop_playing_scene()` is already called at the end of `_on_run_pressed()` and in `_on_debug_pressed()`.

**Comment by AlexDarigan** [comment]
I can't find where I made the change but this seems to have been removed in the dev branch.
