### ISSUE TITLE
C#. Test Assert.IsNotEqual(true, null) does not pass

### ISSUE THREAD

**Issue by fhgaha** [AlexDarigan/WAT#351]
Test methods:
```
[Test]
public void TestIsNotEqual_True_Null()
{
	Assert.IsNotEqual(true, null);
}

[Test]
public void TestIsEqual_False_TrueEqualsNull()
{
	Assert.IsEqual(false, true == null);
}
```
Result:
<img width="539" alt="PRuimW91kB" src="https://user-images.githubusercontent.com/84946584/184520711-734db3a8-c076-49a3-b7de-f1f676104a09.png">

I suppose both methods should pass

**Comment by Atlinx** [comment]
I think this is caused by the C# code passing the assert logic back into GDScript, which has truthy and falsy interpretations of different types. So null ends up being considered falsy here.

**Comment by AlexDarigan** [comment]
Solved by #353

**Comment by fhgaha** [comment]
you probably meant issue #350

**Comment by AlexDarigan** [comment]
> you probably meant issue #350

Woops. Thanks.
