### ISSUE TITLE
C#. Please do not unfold test class lines in editor on RunAll

### ISSUE THREAD

**Issue by fhgaha** [AlexDarigan/WAT#352]

**Comment by AlexDarigan** [comment]
I'll add a toggle

**Comment by AlexDarigan** [comment]
Resolved in a82c41889ea5ac8ae6af5ac39f8d2fd47b3db55c

![image](https://user-images.githubusercontent.com/47497501/234692165-13e19ecc-5359-4c79-90f3-97ca227707cb.png)

![image](https://user-images.githubusercontent.com/47497501/234692314-bd19e543-13db-46ba-875e-9ea4d5a63ccf.png)
