### ISSUE TITLE
Document --no-window for CLI / IDE use cases.

### ISSUE THREAD

**Issue by knightofiam** [AlexDarigan/WAT#356]
Even when specifying ```res://addons/WAT/cli.tscn``` in an external IDE configuration, an empty game window still appears while running tests on the command line, which is completely unexpected. It took me a long while to figure out to specify a ```--no-window``` Godot flag to get rid of this. It would be nice to explain that while WAT itself can't hide the game window in CLI mode, it can be hidden with this flag, since I can't imagine people would want to see an empty game window while running tests in a CLI.

**Comment by AlexDarigan** [comment]
Merging with #369
