### ISSUE TITLE
Github Actions Error: "WARNING: WAT: Could not update filesystem"

### ISSUE THREAD

**Issue by Atlinx** [AlexDarigan/WAT#374]
Hey all, I'm getting this error when I run my unit tests in Github Actions:

```bash
WARNING: WAT: Could not update filesystem
     at: call (modules/gdscript/gdscript_functions.cpp:7[8](https://github.com/Fractural/FracturalSceneManagement/actions/runs/4987206565/jobs/8928739100#step:9:9)[9](https://github.com/Fractural/FracturalSceneManagement/actions/runs/4987206565/jobs/8928739100#step:9:10))
WARNING: WAT: No tests found
     at: call (modules/gdscript/gdscript_functions.cpp:789)
```

Here's a link to my actions on my Github Repo:
https://github.com/Fractural/FracturalInject/actions/runs/4987293388/jobs/8928921285

**Comment by Atlinx** [comment]
Turns out Godot doesn't like case-sensitive folder path names. I had my tests folder named "Tests", however even though WAT was looking for "res://Tests", it still couldn't find the tests folder. Changing the folder in WAT's settings back to "res://tests" fixed it. It's weird that I didn't have to renamed the Tests folder in the end -- I only had to change any loading calls (like file.Open, GD.Load , etc.) to use the lowercase name.

**Comment by AlexDarigan** [comment]
I'm going to reopen this because it sounds concerning. Need to double check if this is really Godot or if I did something weird.

**Comment by AlexDarigan** [comment]
@Atlinx What system (linux, windows etc) did this problem occur on?

**Comment by AlexDarigan** [comment]
@Atlinx 

This is a github issue. The repo you're cloning from uses "tests", not "Tests". Renaming folders is a huge pain in the ass on github since it doesn't do it automatically even if you do.

Relevant commit: https://github.com/Fractural/FracturalInject/tree/cb3d1247817ccc4997ed8857fa57063bdd195f89

**Comment by Atlinx** [comment]
ahh that makes a lot of sense. Tysm for figuring it out!
