### ISSUE TITLE
Implement Fluent Assertions

### ISSUE THREAD

**Issue by AlexDarigan** [AlexDarigan/WAT#43]
Basically change expectations that exist now to fluent assertions.

ie

asserts.has(value, container, context)

we would do

asserts.collection(collection).has(item).give_context("string")

or something like that.

**Comment by CodeDarigan** [comment]
Here is a test example.

extends Node

### BEGIN EXAMPLE USE ###
var list = [1, 5, 10, 4, 2, 5]

func _ready():
	Assert(list).Has(10).And().HasLength(6)
### END EXAMPLE USE ###

### BEGIN Fluent Assertion Buider ###
var system_under_test
	
func Assert(value):
	system_under_test = value
	return self
	
func Has(value):
	var success: bool = value in system_under_test
	print("data has value") if success else print("data does not have value")
	return self
	
func And():
	return self
	
func HasLength(length: int):
	var success: bool = system_under_test.size() == length
	print("data is size") if success else print("data is not size")
### END FLUENT ASSERTION BUILDER ###

**Comment by CodeDarigan** [comment]
Benching this for the release after this one.

**Comment by AlexDarigan** [comment]
Opening unresolved issue.
