### ISSUE TITLE
Add Windows-Godot Container Image for CI

### ISSUE THREAD

**Issue by AlexDarigan** [AlexDarigan/WAT#55]
Currently using a Linux-Godot3.2 Image on CIrcleCI. Should add a windows as well.

**Comment by CodeDarigan** [comment]
It seems setting up this may be non-trivial compared to linux. Since my primary machine is windows, I'll test locally on it for now.

**Comment by AlexDarigan** [comment]
Reopening unresolved issue.

**Comment by AlexDarigan** [comment]
Closing in favor of #361
