### ISSUE TITLE
Add Option To Rerun Failures (Only and or First)

### ISSUE THREAD

**Issue by AlexDarigan** [AlexDarigan/WAT#86]
We may not want to rerun passing tests when trying to fix failures. We could introduce an option to rerun the failed tests from our previous run. We could have this option specifically run ONLY the failed tests (even ignoring passing methods within the test script).

With this enabled, users could also tell their CI platforms to rerun their failed tests for an automated defect localization.

**Comment by CodeDarigan** [comment]
I'll likely choose to rerun only the failures. The rerunning first may cause unnecessary issues and just ends up slowing down the issue anyway.

**Comment by CodeDarigan** [comment]
Closing. See #132.

**Comment by AlexDarigan** [comment]
Opening apparently unresolved issue (might be resolved)

**Comment by AlexDarigan** [comment]
Seems this issue was already resolved in #132

see: https://github.com/AlexDarigan/WAT/issues/132#issuecomment-619452345
