### ISSUE TITLE
Retrieve Method Keywords Automatically When Doubling

### ISSUE THREAD

**Issue by AlexDarigan** [AlexDarigan/WAT#87]
Currently WAT uses partial doubling by default. This means it is up to the user to define which methods get stubbed or not. Everything else keeps its working structure. When modifying a special method this way (remote, puppet, master, sync & static) it is up to the user to tell WAT that it has a keyword.

The only obvious way to do this would be a somewhat confusing string parsing method through the source code of the script.

**Comment by CodeDarigan** [comment]
Going to bench this until at least annotations are added to godot.

**Comment by AlexDarigan** [comment]
Opening unresolved issue.

**Comment by AlexDarigan** [comment]
Reopening this issue because of what I said in #308 where we can use a mix of get_script().get_script_method_list() and regex to find ("keyword func name")

**Comment by AlexDarigan** [comment]
Resolved by #373
